[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Thêm các dòng này vào để tự tải thư viện:
lib_deps =
    bblanchon/ArduinoJson @ ^7.1.0
    madhephaestus/ESP32Servo
    marcoschwartz/LiquidCrystal_I2C